### ISSUE TITLE
Build error for openvx_turotial

### ISSUE THREAD

**Issue by tapanforce** [rgiduthuri/openvx_tutorial#1]
I am completely new to OpenVX and trying to get my hands dirty with this tutorial that is pasted on Khronos website.

My build environment is Linux System.  Here is more information
uname -a
Linux tapan-desktop 3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:39:31 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I am seeing some build error while doing manually build and also using QtCreator tool.  Build error is coming from exercise3.

Here is the error that I am observing.
[ 85%] Building CXX object solution_exercise3/CMakeFiles/solution_exercise3.dir/solution_exercise3.cpp.o
[ 90%] Linking CXX executable solution_exercise3
CMakeFiles/solution_exercise3.dir/solution_exercise3.cpp.o: In function `median_blur_host_side_function(_vx_node*, _vx_reference* const*, unsigned int)':
solution_exercise3.cpp:(.text+0x78d): undefined reference to`vxReadScalarValue'
collect2: ld returned 1 exit status
make[2]: **\* [solution_exercise3/solution_exercise3] Error 1
make[1]: **\* [solution_exercise3/CMakeFiles/solution_exercise3.dir/all] Error 2
make: **\* [all] Error 2
14:09:58: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project tutorial_exercises (kit: Desktop Qt 5.7.0 GCC 64bit)
When executing step "Make"

Can you tell me what can cause this?

**Comment by rgiduthuri** [comment]
BTW, Did you get this error even after following all the instructions in
step 3 of README.md?
[https://github.com/rgiduthuri/openvx_tutorial/blob/master/README.md]
Try  % cmake ../tutorial_exercises and let me know if you still see the
problem.

**Comment by tapanforce** [comment]
Yes.   I am still seeing the same error.

This is my directory structure
drwxr-xr-x  8 tapan tapan  4096 Jun 23 18:38 .
drwxrwxr-x  8 tapan tapan  4096 Jun 16 13:51 ..
drwxrwxr-x 13 tapan tapan  4096 Jun 23 18:38 build-open-source
drwxrwxr-x 13 tapan tapan  4096 Jun 16 13:47 build-tutorial_exercises-Desktop_Qt_5_7_0_GCC_64bit-Default
drwxrwxr-x  8 tapan tapan  4096 Jun 12 16:39 .git
-rw-rw-r--  1 tapan tapan   403 Jun 12 16:39 .gitignore
-rw-rw-r--  1 tapan tapan  1082 Jun 12 16:39 LICENSE
-rw-rw-r--  1 tapan tapan 13712 Jun 12 16:39 README.md
drwxrwxr-x  2 tapan tapan  4096 Jun 12 16:39 scripts
drwxrwxr-x 14 tapan tapan  4096 Jun 16 13:44 tutorial_exercises
drwxrwxr-x  2 tapan tapan  4096 Jun 14 21:32 tutorial_videos

I am using following commands:
cd build-open-source
cmake ../tutorial_exercises
make

Here is the exact error that I am seeing.
....
[ 90%] Linking CXX executable solution_exercise3
CMakeFiles/solution_exercise3.dir/solution_exercise3.cpp.o: In function `median_blur_host_side_function(_vx_node*, _vx_reference* const*, unsigned int)':
solution_exercise3.cpp:(.text+0x78d): undefined reference to`vxReadScalarValue'
collect2: ld returned 1 exit status
make[2]: **\* [solution_exercise3/solution_exercise3] Error 1
make[1]: **\* [solution_exercise3/CMakeFiles/solution_exercise3.dir/all] Error 2
make: **\* [all] Error 2

Let me know if you can help.

Thanks,
Tapan

**Comment by citrix123** [comment]
Hi Tapan,
Are you still facing the problem ?
I am not sure why you are getting the undefined reference , But i will suggest to install all the openvx_sample to your Library path

Try the Following Steps:
1. You may try cloning `https://github.com/kislayabhi/openvx_sample` 
2. Delete the build dir from here else you will face path issue.
3. python Build.py --os=Linux (this will do every thing till make)
4. make install
5. now open openvx_turotial project in Qtcreator and then it will ask for run cmake. do it . (No Arguments need) , now click on Run.
6. That's it . Project is ready

PS: Well i prefered to make it in the console, But worked in rather way
