### ISSUE TITLE
application hang when running any exercises/solution/exercises

### ISSUE THREAD

**Issue by zyclonb** [rgiduthuri/openvx_tutorial#10]
Hi,

I followed section 3 "Build on Linux PC" and section 3.1 "Build on open source OpenVX". The build was successful but whe I tried to run the binary, it hang, without any information printed.

Thanks,
Dexian

**Comment by rgiduthuri** [comment]
It seems to work just fine for me. Could you please try running the same with develop branch of amdovx-core?

**Comment by zyclonb** [comment]
Hi Radha,

It was environment issue and has been fixed. Thanks!

Dexian

发自我的 iPhone

在 2017年11月24日，13:40，Radha Giduthuri <notifications@github.com<mailto:notifications@github.com>> 写道：


It seems to work just fine for me. Could you please try running the same with develop branch of amdovx-core?
