### ISSUE TITLE
gui.GetWidth returning 0

### ISSUE THREAD

**Issue by tusharc7360** [rgiduthuri/openvx_tutorial#11]
Hi,

I am getting error : failed with status = (-10) while creating object:
 vx_image input_rgb_image = vxCreateImage(context, width, height, VX_DF_IMAGE_RGB );
This is because width I am passing has a 0 value.

Thanks,
Tushar

**Comment by rgiduthuri** [comment]
The problem could be with the installed OpenCV library because GetWidth just calls OpenCV library.
The PETS09-S1-L1-View001.avi resolution is 768x480. Try harding coding these values in GetWidth() and GetHeight() to workaround the problem with OpenCV.
