### ISSUE TITLE
Getting error "‘struct _vx_graph’ has no member named ‘enable_node_level_opencl_flush’"

### ISSUE THREAD

**Issue by TurboGurra** [rgiduthuri/openvx_tutorial#12]
Hi, when I try to use 'make' in my build folder after creating it with cmake, I get the following error:

/home/thisuser/Desktop/openvx_tutorial-master/tutorial_exercises/amdovx-core/openvx/ago/ago_interface.cpp: In function ‘vx_status agoDirective(vx_reference, vx_enum)’:
/home/thisuser/Desktop/openvx_tutorial-master/tutorial_exercises/amdovx-core/openvx/ago/ago_interface.cpp:2315:31: error: ‘struct _vx_graph’ has no member named ‘enable_node_level_opencl_flush’
      ((AgoGraph *)reference)->enable_node_level_opencl_flush = false;

Am I missing a package here or something? (I am using Ubuntu 16.04.3 LTS)

**Comment by rgiduthuri** [comment]
@TurboGurra Thanks for reporting the problem. This build error is fixed in develop branch.
Please checkout 'develop' branch and try the same.

**Comment by TurboGurra** [comment]
Where can I find this branch? It is not listed in the branches section.

**Comment by rgiduthuri** [comment]
Try this:
````
% cd openvx_tutorial/tutorial_exercises/amdovx-core
% git checkout develop
% git pull
````

**Comment by TurboGurra** [comment]
It successfully compiled now, thank you very much!
