### ISSUE TITLE
What is the License for video sequence PETS09-S1-L1-View001.avi?

### ISSUE THREAD

**Issue by h-gou** [rgiduthuri/openvx_tutorial#16]
Hello,

We are planning to use the OpenVx tutorial example (solution 1) as an Out of Box demo, and need to include the test clip below in our release. 

Video clip: http://ewh.ieee.org/r6/scv/sps/openvx-material/PETS09-S1-L1-View001.avi (specified in scripts/download-videos.sh)

We are wondering how this avi video is licensed, and if we can release it through our product. Does it also have MIT license as the OpenVx Tutorial source code?

Thanks,
Hongmei

**Comment by rgiduthuri** [comment]
Hi Hongmei, I’m not sure about the license of this video, so didn’t include it in the tutorial repo. 

You may want to contact below link for license information:
http://cs.binghamton.edu/~mrldata/pets2009.html

If you find license info, please do share with other.

**Comment by h-gou** [comment]
Thanks Radha. The original source of the video clip data came from University of Reading at UK: http://www.cvg.reading.ac.uk/PETS2009/a.html

The legal note at the end of the page says:
“Legal note: The video sequences are copyright University of Reading and permission is hereby granted for free download for the purposes of the PETS 2009 workshop and academic and industrial research. Where the data is disseminated (e.g. publications, presentations) the source should be acknowledged.”

**Comment by rgiduthuri** [comment]
Thanks @h-gou.
