### ISSUE TITLE
openvx sample 1.2 issue not working 

### ISSUE THREAD

**Issue by pankajbadatia** [rgiduthuri/openvx_tutorial#18]

**Comment by pankajbadatia** [comment]
Atleast provide a working openvx_sample 1.2 or linux vm that has this sample running properly

**Comment by pankajbadatia** [comment]
Thanks to all who are  so quick to response . Infact from there busy schedule . you all are giving us time for this community.

**Comment by rgiduthuri** [comment]
In case of urgency/no-response, you can reach out to khronos OpenVX forum: https://forums.khronos.org/forumdisplay.php/110-OpenVX
