### ISSUE TITLE
Where is argmax.cpp file?

### ISSUE THREAD

**Issue by srohit0** [rgiduthuri/openvx_tutorial#19]
Where is argmax.cpp file mentioned in the [vgg16-nnef-openvx tutorial](https://github.com/rgiduthuri/openvx_tutorial/tree/master/tutorial_exercises/vgg16-nnef-openvx)?

***Excerpt from [README](https://github.com/rgiduthuri/openvx_tutorial/tree/master/tutorial_exercises/vgg16-nnef-openvx)***

---
>  You can use argmax.cpp file to get the classification label.
```
% g++ argmax.c++ -o argmax
% ./argmax output.f32 labels.txt
```
---
Is user expected to write this file? If yes, is there a template to follow for beginners to create this file?

**Comment by lcskrishna** [comment]
Yes, @srohit0  you can write one. 
There is no template to do that, and feel free to contribute to this repository.
