### ISSUE TITLE
solution_exercise1

### ISSUE THREAD

**Issue by ghost** [rgiduthuri/openvx_tutorial#2]
Dears,

I'm new to OpenVX and starting with, I'm able to run "solution_exercise1solution_exercise1.exe" @ Windows. Now I'd like to connect with integrated webcam.

c:\openvx_tutorial\build-open-source\Debug>solution_exercise1.exe 0
****\* VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****
ERROR: unable to open: 0

I'm not able to open webcam - what's right approach to get webcam stream?
Thanks.

**Comment by gshisha** [comment]
Can you confirm if it is one of these lines causing the abort?

> > > > ```
> > > > CGuiModule gui( video_sequence );
> > > > if( !gui.Grab() )
> > > > ```
> > > > 
> > > > <<<<

It is possible that the webcam camera id is 1 (or 2, instead of 0) on your system, so please try that in the command-line like this:
// Command-line usage:
//   % solution_exercise1 [<video-sequence>|<camera-device-number>]

**Comment by gshisha** [comment]
% solution_exercise1 1
