### ISSUE TITLE
vxCreateContext() not success; 

### ISSUE THREAD

**Issue by xqch1983** [rgiduthuri/openvx_tutorial#3]
vx_context context = vxCreateContext() ; if (vxGetStatus((vx_reference)context) == VX_SUCCESS) return value 0 or vxCreateContext() call not succuss,  can you tell me where is the problme comming from?
thanks.

**Comment by rgiduthuri** [comment]
Below is the correct usage:
  **vx_context context = vxCreateContext();
  vx_status status = vxGetStatus((vx_reference)context);
  if(status != VX_SUCCESS) {
    // error handling
  }**

What is the value of status returned by vxGetStatus()?
