### ISSUE TITLE
Error while building Openvx_tutorial on Jetson TX1

### ISSUE THREAD

**Issue by Eyshika** [rgiduthuri/openvx_tutorial#7]
I am working on one of my compute vision project where I am using NVidia Jetson TX1 which came up with Visionworks lib, opencv and cuda, I installed everything successfully, but when I tried to build openvx_tutorial on qt creator after cloning it from here. i got a an error: cannot find-lopencv_dep_cudart.

I didnt change anything in cmakelist file, still i dont know from where and why it came up. Do I need to do some changes ? please help.
Also, I am in leaning stage of openvx, kindly guide me how to start openvx programming.

**Comment by lcskrishna** [comment]
https://devtalk.nvidia.com/default/topic/970325/cmake-cannot-find-lopencv_dep_cudart/
Check this out, someone seems to have a similar problem.

**Comment by Eyshika** [comment]
hey, i followed that and i was able to remove the error of opencv by setting CUDA_RUNTIME off, it ran but not able to open video now.
Does it mean this tutorial needs RUNTIME to be ON ?

**Comment by lcskrishna** [comment]
I don't have Jetson with me, so can't tell you exactly what's the issue is. 
But in case if you want to link the libraries, you can modify in the CMake file in example folders and try it out. 
Ex: 
link_directories        ( ${OpenVX_LIBS_DIR}     <Your_DIR> )

Chaitanya.

**Comment by Eyshika** [comment]
when I am trying to link the directories Cmake list shows an error of not needed opencv files. Do you know someone who have worked on Jetson ?

**Comment by rgiduthuri** [comment]
@Eyshika please reopen this issue if you see any problem with this project.
